env:
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  'no-console': 'off'
  'import/extensions': 'off'
  "fp/no-mutation": "off"
ignorePatterns:
  - 'dist/*'
  - 'project/code/dist/*'
plugins:
  - 'import'
  - 'fp'
overrides:
    - files:
      - '*.ts'
      - '*.tsx'
      extends:
        - airbnb-base
        - airbnb-typescript/base
      parser: '@typescript-eslint/parser'
      parserOptions:
        project: './tsconfig.json'
      plugins:
        - '@typescript-eslint'
      rules:
        'no-console': 'off'
        'import/extensions': 'off'
        'import/prefer-default-export': 'off'

